name: Build GUI exe with Pyinstaller

on:
  push:
  workflow_run:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src/

    - uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: src/dist/*
